workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - Apple Credentials
      xcode: latest
      cocoapods: default
      flutter: stable
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"  # Remplacez par le nom de votre workspace si différent
        XCODE_SCHEME: "Runner"  # Remplacez par le nom de votre scheme si différent
        BUNDLE_ID: "com.h24consulting.appariteur"  # Remplacez par votre Bundle ID

    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Launch iOS Simulator and Run App
        script: |
          # Lancer le simulateur et attendre qu'il soit prêt
          xcrun simctl boot D3F41A76-A956-4F9B-8874-99974B22C923
          xcrun simctl shutdown D3F41A76-A956-4F9B-8874-99974B22C923 || true
          xcrun simctl boot D3F41A76-A956-4F9B-8874-99974B22C923
          
          # Installer l'application sur le simulateur
          xcrun simctl install D3F41A76-A956-4F9B-8874-99974B22C923 build/ios/iphonesimulator/Runner.app
          
          # Lancer l'application sur le simulateur
          xcrun simctl launch D3F41A76-A956-4F9B-8874-99974B22C923 com.h24consulting.appariteur

          # Capturer les logs du simulateur
          xcrun simctl spawn D3F41A76-A956-4F9B-8874-99974B22C923 log collect --output /tmp/simulator_logs.log
          
          # Optionnel : Télécharger les logs
          curl -F "file=@/tmp/simulator_logs.log" https://your-log-upload-server.com/upload
