workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_PROJECT: "Runner.xcodeproj"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.app"
        APP_NAME: "My App"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build ipa
        script: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          xcodebuild -exportArchive -exportOptionsPlist exportOptions.plist -archivePath "${APP_NAME}.xcarchive" -exportPath "${APP_NAME}"
    artifacts:
      - build/ios/iphoneos/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log