workflows:
  ios-app:
    name: Appariteur
    max_build_duration: 120
    instance_type: mac_mini
    environment:
      vars:
      # Add your environment variables here
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '^main$'
          include: true
          source: true
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "io.appariteur.app" --type IOS_APP_STORE --create
      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Increment build number
        script: agvtool new-version -all $(($(app-store-connect get-latest-app-store-version "io.appariteur.app" --platform IOS + 1)))
      - name: Build ipa for distribution
        script: xcode-project build-ipa --project "ios/Runner.xcodeproj" --scheme "Runner"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - ios/build/ios/xcarchive/*.xcarchive.zip
    publishing:
      app_store_connect:
        apple_id: your@appleid.com
        password: '@env(APP_STORE_CONNECT_PASSWORD)'
        app_specific_password: '@env(APP_SPECIFIC_PASSWORD)'
        app_identifier: "io.appariteur.app"
