workflows:
  ios-build:
    scripts:
      - name: Flutter build iOS
        script: |
          flutter build ios --release
      - name: Archive app
        script: |
          cd build/ios
          xcodebuild -scheme Runner -configuration Release archive -archivePath $FCI_BUILD_DIR/app.xcarchive -allowProvisioningUpdates -allowProvisioningDeviceRegistration=false
      - name: Export ipa
        script: |
          xcodebuild -exportArchive -archivePath $FCI_BUILD_DIR/app.xcarchive -exportPath $FCI_BUILD_DIR -exportOptionsPlist exportOptions.plist