workflows:
  default-workflow:
    name: Workflow Name
    instance_type: mac_mini
    max_build_duration:  60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ipa --release
    artifacts:
      - build/app/outputs/flutter-ipa/app-release.ipa
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
        - pattern: feature/*
          include: false
        - pattern: develop
          include: false
        - pattern: release/*
          include: true

