workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
        - pattern: feature/*
          include: false
        - pattern: develop
          include: false
        - pattern: release/*
          include: true