workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_PROJECT: "Runner.xcodeproj"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.appariteur.app"
        APP_NAME: "Appariteur"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build iOS app
        script: |
          flutter build ios --release
          cd build/ios
          xcodebuild -scheme Runner archive -archivePath $FCI_BUILD_DIR/Runner.xcarchive
      - name: Export ipa
        script: |
          xcodebuild -exportArchive -archivePath "$FCI_BUILD_DIR/Runner.xcarchive" -exportPath "$FCI_BUILD_DIR" -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/ios/iphoneos/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log